states_dict = {
			"AP": "Andhra Pradesh", 	
			"AR": "Arunachal Pradesh", 	
			"AS": "Assam", 	
			"BR": "Bihar", 	
			"CT": "Chhattisgarh", 	
			"DL": "Delhi", 	
			"GA": "Goa", 	
			"GJ": "Gujarat", 	
			"HR": "Haryana", 	
			"HP": "Himachal Pradesh", 	
			"JK": "Jammu & Kashmir", 	
			"JH": "Jharkhand", 	
			"KA": "Karnataka", 	
			"KL": "Kerala", 	
			"LA": "Ladakh",
			"MP": "Madhya Pradesh", 	
			"MH": "Maharashtra", 	
			"MN": "Manipur", 	
			"ML": "Meghalaya", 	
			"MZ": "Mizoram", 	
			"NL": "Nagaland", 	
			"OR": "Orissa", 	
			"PB": "Punjab", 	
			"RJ": "Rajasthan", 	
			"SK": "Sikkim", 	
			"TG": "Telangana",
			"TN": "Tamil Nadu", 	
			"TR": "Tripura", 	
			"UT": "Uttarakhand Uttranchal",
			"UP": "Uttar Pradesh", 	
			"WB": "West Bengal", 	
			"AN": "Andaman & Nicobar", 	
			"CH": "Chandigarh", 	
			"DN": "Dadra and Nagar Haveli", 	
			"DD": "Daman & Diu", 	
			"LD": "Lakshadweep", 	
			"PY": "Pondicherry", 

			# Other Code
			"TT": "Total_Testing",
		}