states_dict = {
			"Andhra Pradesh" : "AP",
			"Arunachal Pradesh" : "AR",
			"Assam" : "AS",
			"Bihar" : "BR",
			"Chhattisgarh" : "CT",
			"Delhi" : "DL",
			"Goa" : "GA",
			"Gujarat" : "GJ",
			"Haryana" : "HR",
			"Himachal Pradesh" : "HP",
			"Jammu and Kashmir" : "JK",
			"Jharkhand" : "JH",
			"Karnataka" : "KA",
			"Kerala" : "KL",
			"Ladakh" : "LA",
			"Madhya Pradesh" : "MP",
			"Maharashtra" : "MH",
			"Manipur" : "MN",
			"Meghalaya" : "ML",
			"Mizoram" : "MZ",
			"Nagaland" : "NL",
			"Odisha" : "OR",
			"Punjab" : "PB",
			"Rajasthan" : "RJ",
			"Sikkim" : "SK",
			"Telangana" : "TG",
			"Tamil Nadu" : "TN",
			"Tripura" : "TR",
			"Uttarakhand" : "UT",
			"Uttar Pradesh" : "UP",
			"West Bengal" : "WB",
			"Andaman and Nicobar Islands" : "AN",
			"Chandigarh" : "CH",
			"Dadra and Nagar Haveli and Daman and Diu" : "DN",
			"Daman & Diu" : "DD",
			"Lakshadweep" : "LD",
			"Puducherry" : "PY",

			# Other Code
			"India" : "TT",
		}


# # states_dict = {
# 			"AP": "Andhra Pradesh", 	
# 			"AR": "Arunachal Pradesh", 	
# 			"AS": "Assam", 	
# 			"BR": "Bihar", 	
# 			"CT": "Chhattisgarh", 	
# 			"DL": "Delhi", 	
# 			"GA": "Goa", 	
# 			"GJ": "Gujarat", 	
# 			"HR": "Haryana", 	
# 			"HP": "Himachal Pradesh", 	
# 			"JK": "Jammu & Kashmir", 	
# 			"JH": "Jharkhand", 	
# 			"KA": "Karnataka", 	
# 			"KL": "Kerala", 	
# 			"LA": "Ladakh",
# 			"MP": "Madhya Pradesh", 	
# 			"MH": "Maharashtra", 	
# 			"MN": "Manipur", 	
# 			"ML": "Meghalaya", 	
# 			"MZ": "Mizoram", 	
# 			"NL": "Nagaland", 	
# 			"OR": "Orissa", 	
# 			"PB": "Punjab", 	
# 			"RJ": "Rajasthan", 	
# 			"SK": "Sikkim", 	
# 			"TG": "Telangana",
# 			"TN": "Tamil Nadu", 	
# 			"TR": "Tripura", 	
# 			"UT": "Uttarakhand Uttranchal",
# 			"UP": "Uttar Pradesh", 	
# 			"WB": "West Bengal", 	
# 			"AN": "Andaman & Nicobar", 	
# 			"CH": "Chandigarh", 	
# 			"DN": "Dadra and Nagar Haveli", 	
# 			"DD": "Daman & Diu", 	
# 			"LD": "Lakshadweep", 	
# 			"PY": "Pondicherry", 

# 			# Other Code
# 			"TT": "Total_Testing",
# 		}