# Generated by Django 3.1.2 on 2020-10-16 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number Enter in 10 Digit Formate', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(max_length=250)),
                ('number_of_beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must be Greater than Zero')])),
                ('hospital_contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number Enter in 10 Digit Formate', regex='^\\d{10}$')])),
                ('hospital_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('insurance_facility', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
                ('ventilator_facility', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
                ('address', models.CharField(max_length=500)),
                ('hospital_website', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must be Greater than Zero'), django.core.validators.MaxValueValidator(limit_value=100, message='Must be less than or Equal to 100')])),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number Enter in 10 Digit Formate', regex='^\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='VaccineUpdatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=700)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
