# Generated by Django 3.1.2 on 2020-10-10 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must be Greater than Zero'), django.core.validators.MaxValueValidator(limit_value=100, message='Must ve less than or Equal to 100')])),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number Enter in 10 Digit Formate', regex='^\\d10$')])),
            ],
        ),
    ]
