# Generated by Django 3.1.2 on 2020-10-10 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=250)),
                ('number_of_beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must be Greater than Zero')])),
                ('hospital_email', models.EmailField(max_length=254)),
                ('insurance_facility', models.CharField(max_length=3)),
                ('ventilator_facility', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=500)),
                ('hospital_website', models.URLField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='vaccineupdate',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number Enter in 10 Digit Formate', regex='^\\d{10}$')]),
        ),
    ]
