# Generated by Django 3.1.2 on 2020-10-10 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201010_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregister',
            name='mobile_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number Enter in 10 Digit Formate', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
