# Generated by Django 3.1.2 on 2020-10-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hitcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineupdatepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
