# Generated by Django 3.1.2 on 2020-10-27 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vaccineupdatepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregister',
            name='hospital_landline',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="LandLine Number Enter in 12 Digit Formate - If It's less than 12 Digit try with leading number as 0 and make it 12", regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='vaccineupdate',
            name='landline_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="LandLine Number Enter in 12 Digit Formate - If It's less than 12 Digit try with leading number as 0 and make it 12", regex='^\\d{12}$')]),
        ),
    ]
