# Generated by Django 3.1.2 on 2020-10-11 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201010_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalregister',
            name='city',
        ),
        migrations.AlterField(
            model_name='vaccineupdate',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Must be Greater than Zero'), django.core.validators.MaxValueValidator(limit_value=100, message='Must be less than or Equal to 100')]),
        ),
    ]
