# Generated by Django 3.1.2 on 2020-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201011_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregister',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
