# Generated by Django 3.1.2 on 2020-11-06 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201027_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile Number Enter in 10 Digit Formate', regex='^\\d{10}$')])),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
